package com.example.sungho.chef.Data;
/**
 * 파이어베이스에 레스토랑 정보 보내기위한 객체
 * Generated by JSW 2019-10-24
 * */
public class RestaurantInfo {
    private String name;
    private String logo;
    private String description;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
